/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * reffer.al
 * OpenAPI spec version: 0.0.1
 */
export type SubscribeToEventBody = {
  name: string;
  email: string;
  /** @nullable */
  referrer?: string | null;
};

export type SubscribeToEvent201 = {
  subscriberID: string;
};

/**
 * @nullable
 */
export type AccessInviteLink302 = typeof AccessInviteLink302[keyof typeof AccessInviteLink302] | null;


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AccessInviteLink302 = {
  null: 'null',
} as const;

export type GetSubscriberInviteClicks200 = {
  count: number;
};

export type GetSubscriberInviteCount200 = {
  count: number;
};

export type GetSubscriberRankingPosition200 = {
  /** @nullable */
  position: number | null;
};

export type GetRanking200RankingItem = {
  id: string;
  name: string;
  score: number;
};

export type GetRanking200 = {
  ranking: GetRanking200RankingItem[];
};

/**
 * @summary Subscribe someone to the event.
 */
export const getSubscribeToEventUrl = () => {


  

  return `http://localhost:3333/subscription`
}

export const subscribeToEvent = async (subscribeToEventBody: SubscribeToEventBody, options?: RequestInit): Promise<SubscribeToEvent201> => {
  
  const res = await fetch(getSubscribeToEventUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      subscribeToEventBody,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()
  const data: SubscribeToEvent201 = body ? JSON.parse(body) : {}

  return data
}



/**
 * @summary Access invite link and redirect user
 */
export const getAccessInviteLinkUrl = (subscriberID: string,) => {


  

  return `http://localhost:3333/invites/${subscriberID}`
}

export const accessInviteLink = async (subscriberID: string, options?: RequestInit): Promise<unknown> => {
  
  const res = await fetch(getAccessInviteLinkUrl(subscriberID),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()
  const data: unknown = body ? JSON.parse(body) : {}

  return data
}



/**
 * @summary Get subscribers invite click count
 */
export const getGetSubscriberInviteClicksUrl = (subscriberID: string,) => {


  

  return `http://localhost:3333/subscribers/${subscriberID}/ranking/clicks`
}

export const getSubscriberInviteClicks = async (subscriberID: string, options?: RequestInit): Promise<GetSubscriberInviteClicks200> => {
  
  const res = await fetch(getGetSubscriberInviteClicksUrl(subscriberID),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()
  const data: GetSubscriberInviteClicks200 = body ? JSON.parse(body) : {}

  return data
}



/**
 * @summary Get subscribers invite count
 */
export const getGetSubscriberInviteCountUrl = (subscriberID: string,) => {


  

  return `http://localhost:3333/subscribers/${subscriberID}/ranking/count`
}

export const getSubscriberInviteCount = async (subscriberID: string, options?: RequestInit): Promise<GetSubscriberInviteCount200> => {
  
  const res = await fetch(getGetSubscriberInviteCountUrl(subscriberID),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()
  const data: GetSubscriberInviteCount200 = body ? JSON.parse(body) : {}

  return data
}



/**
 * @summary Get subscribers ranking position
 */
export const getGetSubscriberRankingPositionUrl = (subscriberID: string,) => {


  

  return `http://localhost:3333/subscribers/${subscriberID}/ranking/position`
}

export const getSubscriberRankingPosition = async (subscriberID: string, options?: RequestInit): Promise<GetSubscriberRankingPosition200> => {
  
  const res = await fetch(getGetSubscriberRankingPositionUrl(subscriberID),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()
  const data: GetSubscriberRankingPosition200 = body ? JSON.parse(body) : {}

  return data
}



/**
 * @summary Get ranking
 */
export const getGetRankingUrl = () => {


  

  return `http://localhost:3333/ranking`
}

export const getRanking = async ( options?: RequestInit): Promise<GetRanking200> => {
  
  const res = await fetch(getGetRankingUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()
  const data: GetRanking200 = body ? JSON.parse(body) : {}

  return data
}
