services:
  reffer_al-postgres:
    image: bitnami/postgresql
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=reffer_al

  reffer_al-redis:
    image: bitnami/redis
    ports:
      - '6379:6379'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
